/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ImageprocessingParameterDef } from "./components/imageprocessing-parameters/definition";
export namespace Components {
    interface BarcodeFormats {
        /**
          * Update checked barcode formats with an object like the following: {   "BarcodeFormatIds": [     "BF_EAN_13"   ],   "BarcodeFormatIds_2": [     "BF2_POSTALCODE"   ], }
         */
        "loadSettings": (settings: any) => Promise<void>;
        /**
          * Output checked barcode formats to an object like the following: {   "BarcodeFormatIds": [     "BF_EAN_13"   ],   "BarcodeFormatIds_2": [     "BF2_POSTALCODE"   ], }
         */
        "outputSettings": () => Promise<any>;
    }
    interface ImageprocessingParameters {
        "loadExternalDefinition": (defs: ImageprocessingParameterDef[]) => Promise<void>;
        "loadSettings": (params: any) => Promise<void>;
        "outputSettings": () => Promise<{}>;
    }
}
declare global {
    interface HTMLBarcodeFormatsElement extends Components.BarcodeFormats, HTMLStencilElement {
    }
    var HTMLBarcodeFormatsElement: {
        prototype: HTMLBarcodeFormatsElement;
        new (): HTMLBarcodeFormatsElement;
    };
    interface HTMLImageprocessingParametersElement extends Components.ImageprocessingParameters, HTMLStencilElement {
    }
    var HTMLImageprocessingParametersElement: {
        prototype: HTMLImageprocessingParametersElement;
        new (): HTMLImageprocessingParametersElement;
    };
    interface HTMLElementTagNameMap {
        "barcode-formats": HTMLBarcodeFormatsElement;
        "imageprocessing-parameters": HTMLImageprocessingParametersElement;
    }
}
declare namespace LocalJSX {
    interface BarcodeFormats {
    }
    interface ImageprocessingParameters {
    }
    interface IntrinsicElements {
        "barcode-formats": BarcodeFormats;
        "imageprocessing-parameters": ImageprocessingParameters;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "barcode-formats": LocalJSX.BarcodeFormats & JSXBase.HTMLAttributes<HTMLBarcodeFormatsElement>;
            "imageprocessing-parameters": LocalJSX.ImageprocessingParameters & JSXBase.HTMLAttributes<HTMLImageprocessingParametersElement>;
        }
    }
}
