/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BarcodeFormats {
    }
    interface BinarizationModes {
    }
}
declare global {
    interface HTMLBarcodeFormatsElement extends Components.BarcodeFormats, HTMLStencilElement {
    }
    var HTMLBarcodeFormatsElement: {
        prototype: HTMLBarcodeFormatsElement;
        new (): HTMLBarcodeFormatsElement;
    };
    interface HTMLBinarizationModesElement extends Components.BinarizationModes, HTMLStencilElement {
    }
    var HTMLBinarizationModesElement: {
        prototype: HTMLBinarizationModesElement;
        new (): HTMLBinarizationModesElement;
    };
    interface HTMLElementTagNameMap {
        "barcode-formats": HTMLBarcodeFormatsElement;
        "binarization-modes": HTMLBinarizationModesElement;
    }
}
declare namespace LocalJSX {
    interface BarcodeFormats {
    }
    interface BinarizationModes {
    }
    interface IntrinsicElements {
        "barcode-formats": BarcodeFormats;
        "binarization-modes": BinarizationModes;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "barcode-formats": LocalJSX.BarcodeFormats & JSXBase.HTMLAttributes<HTMLBarcodeFormatsElement>;
            "binarization-modes": LocalJSX.BinarizationModes & JSXBase.HTMLAttributes<HTMLBinarizationModesElement>;
        }
    }
}
